// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkfkdlfovaelhqbgjkja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrZmtkbGZvdmFlbGhxYmdqa2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjEzNjcsImV4cCI6MjA3MDUzNzM2N30.mYdHnk0Y54rKiK31t8QEfQiOSjnuzW-EtipYm2lHcL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});